### ISSUE TITLE
[Feature] Add post-ids before links

### ISSUE THREAD

**Issue by ClonedBoy** [Garcarius/forumslinkgraber#6]
Hi! This is nice script that I've been using since the drop of SC. Thanks, it is really neat!

Could an option be added to separate links in posts, so they can be used with the CDL format? For example: insert the post number before the link, like this:

> === post-7552
> https://jpg5.su/img/Link1
> === post-110025
> https://jpg5.su/img/Link2
> https://jpg5.su/img/Link3
> https://jpg5.su/img/Link4
> === post-3912555
> https://vk.com/video/Link

I have tried to edit the code to do so, but my knowledge of JS is very poor and I wouldn't know how to get the post numbers to be appended. Thanks!

**Comment by Garcarius** [comment]
this wont be implemented cause this will make a folder per post and not per model and this was made to merge per model, so this wont have any utility
